# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  simplebankbackend:
    image: simplebankbackend
    build:
      context: .
      dockerfile: src/Backend/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
